# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seventh_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(715, 570)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Palet = QtWidgets.QLabel(self.centralwidget)
        self.Palet.setGeometry(QtCore.QRect(10, 20, 356, 491))
        self.Palet.setText("")
        self.Palet.setObjectName("Palet")
        self.DictLabel = QtWidgets.QLabel(self.centralwidget)
        self.DictLabel.setGeometry(QtCore.QRect(142, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily(".Apple SD Gothic NeoI")
        font.setPointSize(26)
        self.DictLabel.setFont(font)
        self.DictLabel.setObjectName("DictLabel")
        self.NackNarrowImage = QtWidgets.QLabel(self.centralwidget)
        self.NackNarrowImage.setGeometry(QtCore.QRect(30, 70, 41, 41))
        self.NackNarrowImage.setText("")
        self.NackNarrowImage.setObjectName("NackNarrowImage")

        self.gt_WordLabel = QtWidgets.QLabel(self.centralwidget)
        self.gt_WordLabel.setGeometry(QtCore.QRect(510, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily(".Apple SD Gothic NeoI")
        font.setPointSize(18)
        self.gt_WordLabel.setFont(font)
        self.gt_WordLabel.setObjectName("gt_WordLabel")
        self.Palet_2 = QtWidgets.QLabel(self.centralwidget)
        self.Palet_2.setGeometry(QtCore.QRect(390, 90, 301, 321))
        self.Palet_2.setText("")
        self.Palet_2.setObjectName("Palet_2")
        self.SoundImage = QtWidgets.QLabel(self.centralwidget)
        self.SoundImage.setGeometry(QtCore.QRect(510, 270, 51, 41))
        self.SoundImage.setText("")
        self.SoundImage.setObjectName("SoundImage")
        self.backImage = QtWidgets.QLabel(self.centralwidget)
        self.backImage.setGeometry(QtCore.QRect(410, 350, 41, 41))
        self.backImage.setText("")
        self.backImage.setObjectName("backImage")
        self.nextImage = QtWidgets.QLabel(self.centralwidget)
        self.nextImage.setGeometry(QtCore.QRect(630, 350, 41, 41))
        self.nextImage.setText("")
        self.nextImage.setObjectName("nextImage")
        self.wordImage = QtWidgets.QLabel(self.centralwidget)
        self.wordImage.setGeometry(QtCore.QRect(440, 120, 201, 121))
        self.wordImage.setText("")
        self.wordImage.setObjectName("wordImage")
        self.CardsButton = QtWidgets.QPushButton(self.centralwidget)
        self.CardsButton.setGeometry(QtCore.QRect(85, 370, 201, 51))
        font = QtGui.QFont()
        font.setFamily(".Apple SD Gothic NeoI")
        font.setPointSize(24)
        self.CardsButton.setFont(font)
        self.CardsButton.setObjectName("CardsButton")

        self.AddWordButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddWordButton.setGeometry(QtCore.QRect(85, 150, 201, 51))
        font = QtGui.QFont()
        font.setFamily(".Apple SD Gothic NeoI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.AddWordButton.setFont(font)
        self.AddWordButton.setObjectName("AddWordButton")
        self.MyWordsButton = QtWidgets.QPushButton(self.centralwidget)
        self.MyWordsButton.setGeometry(QtCore.QRect(85, 260, 201, 51))
        font = QtGui.QFont()
        font.setFamily(".Apple SD Gothic NeoI")
        font.setPointSize(24)
        self.MyWordsButton.setFont(font)
        self.MyWordsButton.setObjectName("MyWordsButton")
        self.Palet_2.raise_()
        self.Palet.raise_()
        self.DictLabel.raise_()
        self.NackNarrowImage.raise_()
        self.gt_WordLabel.raise_()
        self.SoundImage.raise_()
        self.backImage.raise_()
        self.nextImage.raise_()
        self.wordImage.raise_()
        self.CardsButton.raise_()
        self.AddWordButton.raise_()
        self.MyWordsButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DictLabel.setText(_translate("MainWindow", "Словарь"))
        self.gt_WordLabel.setText(_translate("MainWindow", "машина"))
        self.CardsButton.setText(_translate("MainWindow", "Карточки"))
        self.AddWordButton.setText(_translate("MainWindow", "Добавить слово"))
        self.MyWordsButton.setText(_translate("MainWindow", "Мои слова"))
