# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fifth_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtGui import QGuiApplication

class Ui_View_5(object):
    def setupUi(self, View_5):

        View_5.setObjectName("View_5")
        View_5.resize(715, 570)
        self.centralwidget = QtWidgets.QWidget(View_5)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: #fff")

        self.Palet = QtWidgets.QLabel(self.centralwidget)
        self.Palet.setGeometry(QtCore.QRect(10, 20, 356, 491))
        self.Palet.setText("")
        self.Palet.setObjectName("Palet")
        self.Palet = QtWidgets.QLabel(self.centralwidget)
        self.Palet.setGeometry(QtCore.QRect(20, 20, 341, 500))
        self.Palet.setText("")
        self.Palet.setObjectName("Palet")
        self.Palet.setStyleSheet('''
                                                             background-color: #F6ED9A;
                                                             border-color: #F6ED9A;
                                                             border-width: 2px;
                                                             border-radius: 10px;
                             ''')

        self.DictLabel = QtWidgets.QLabel(self.centralwidget)
        self.DictLabel.setGeometry(QtCore.QRect(142, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(26)
        self.DictLabel.setFont(font)
        self.DictLabel.setObjectName("DictLabel")
        self.DictLabel.setStyleSheet("background-color: #F6ED9A")

        self.NackNarrowImage = QtWidgets.QLabel(self.centralwidget)
        self.NackNarrowImage.setGeometry(QtCore.QRect(30, 70, 41, 41))
        self.NackNarrowImage.setText("")
        self.NackNarrowImage.setObjectName("NackNarrowImage")
        self.NackNarrowImage.setStyleSheet("background-color: #F6ED9A")

        self.AddWordButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddWordButton.setGeometry(QtCore.QRect(90, 150, 201, 51))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(24)
        #font.setBold(False)
        font.setWeight(75)
        self.AddWordButton.setFont(font)
        self.AddWordButton.setObjectName("AddWordButton")
        self.AddWordButton.setStyleSheet("background-color: #F6ED9A")

        self.MyWordsButton = QtWidgets.QPushButton(self.centralwidget)
        self.MyWordsButton.setGeometry(QtCore.QRect(90, 260, 201, 51))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(24)
        self.MyWordsButton.setFont(font)
        self.MyWordsButton.setObjectName("MyWordsButton")
        self.MyWordsButton.setStyleSheet("background-color: #F6ED9A")

        self.CardsButton = QtWidgets.QPushButton(self.centralwidget)
        self.CardsButton.setGeometry(QtCore.QRect(90, 370, 201, 51))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(24)
        self.CardsButton.setFont(font)
        self.CardsButton.setObjectName("CardsButton")
        self.CardsButton.setStyleSheet("background-color: #F6ED9A")

        ### Экран 5 - по кнопке "ДОБАВИТЬ СЛОВО"
        self.gt_WordLabel = QtWidgets.QLabel(self.centralwidget)
        self.gt_WordLabel.setGeometry(QtCore.QRect(400, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(21)
        self.gt_WordLabel.setFont(font)
        self.gt_WordLabel.setObjectName("gt_WordLabel")
        self.gt_WordLabel.hide()

        self.gt_TranslationLabel = QtWidgets.QLabel(self.centralwidget)
        self.gt_TranslationLabel.setGeometry(QtCore.QRect(400, 270, 131, 31))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(21)
        self.gt_TranslationLabel.setFont(font)
        self.gt_TranslationLabel.setObjectName("gt_TranslationLabel")
        self.gt_TranslationLabel.hide()

        self.gt_WordtextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.gt_WordtextEdit.setGeometry(QtCore.QRect(400, 200, 271, 35))
        self.gt_WordtextEdit.setObjectName("gt_WordtextEdit")
        self.gt_WordtextEdit.hide()

        self.gt_TranslationtextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.gt_TranslationtextEdit.setGeometry(QtCore.QRect(400, 300, 271, 35))
        self.gt_TranslationtextEdit.setObjectName("gt_TranslationtextEdit")
        self.gt_TranslationtextEdit.hide()

        ### Экран 6 - по кнопке "МОИ СЛОВА"

        self.VocListLabel = QtWidgets.QLabel(self.centralwidget)
        self.VocListLabel.setGeometry(QtCore.QRect(610, 30, 171, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(24)
        self.VocListLabel.setFont(font)
        self.VocListLabel.setObjectName("VocListLabel")
        self.VL_engWord_1 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engWord_1.setGeometry(QtCore.QRect(400, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engWord_1.setFont(font)
        self.VL_engWord_1.setObjectName("VL_engWord_1")
        self.VL_rusWord_1 = QtWidgets.QLabel(self.centralwidget)
        self.VL_rusWord_1.setGeometry(QtCore.QRect(550, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_rusWord_1.setFont(font)
        self.VL_rusWord_1.setObjectName("VL_rusWord_1")
        self.VL_engTransl_1 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engTransl_1.setGeometry(QtCore.QRect(680, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engTransl_1.setFont(font)
        self.VL_engTransl_1.setAutoFillBackground(False)
        self.VL_engTransl_1.setObjectName("VL_engTransl_1")
        self.VL_engSinonyms_1 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engSinonyms_1.setGeometry(QtCore.QRect(840, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engSinonyms_1.setFont(font)
        self.VL_engSinonyms_1.setAutoFillBackground(False)
        self.VL_engSinonyms_1.setObjectName("VL_engSinonyms_1")
        self.VL_rusWord_2 = QtWidgets.QLabel(self.centralwidget)
        self.VL_rusWord_2.setGeometry(QtCore.QRect(550, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_rusWord_2.setFont(font)
        self.VL_rusWord_2.setObjectName("VL_rusWord_2")
        self.VL_engTransl_2 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engTransl_2.setGeometry(QtCore.QRect(680, 190, 131, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engTransl_2.setFont(font)
        self.VL_engTransl_2.setAutoFillBackground(False)
        self.VL_engTransl_2.setObjectName("VL_engTransl_2")
        self.VL_engSinonyms_2 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engSinonyms_2.setGeometry(QtCore.QRect(840, 190, 131, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engSinonyms_2.setFont(font)
        self.VL_engSinonyms_2.setAutoFillBackground(False)
        self.VL_engSinonyms_2.setObjectName("VL_engSinonyms_2")
        self.VL_engWord_2 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engWord_2.setGeometry(QtCore.QRect(400, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engWord_2.setFont(font)
        self.VL_engWord_2.setObjectName("VL_engWord_2")
        self.VL_rusWord_3 = QtWidgets.QLabel(self.centralwidget)
        self.VL_rusWord_3.setGeometry(QtCore.QRect(550, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_rusWord_3.setFont(font)
        self.VL_rusWord_3.setObjectName("VL_rusWord_3")
        self.VL_engTransl_3 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engTransl_3.setGeometry(QtCore.QRect(680, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engTransl_3.setFont(font)
        self.VL_engTransl_3.setAutoFillBackground(False)
        self.VL_engTransl_3.setObjectName("VL_engTransl_3")
        self.VL_engSinonyms_3 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engSinonyms_3.setGeometry(QtCore.QRect(840, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engSinonyms_3.setFont(font)
        self.VL_engSinonyms_3.setAutoFillBackground(False)
        self.VL_engSinonyms_3.setObjectName("VL_engSinonyms_3")
        self.VL_engWord_3 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engWord_3.setGeometry(QtCore.QRect(400, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engWord_3.setFont(font)
        self.VL_engWord_3.setObjectName("VL_engWord_3")
        self.VL_engSinonyms_4 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engSinonyms_4.setGeometry(QtCore.QRect(840, 370, 131, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engSinonyms_4.setFont(font)
        self.VL_engSinonyms_4.setAutoFillBackground(False)
        self.VL_engSinonyms_4.setObjectName("VL_engSinonyms_4")
        self.VL_engWord_4 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engWord_4.setGeometry(QtCore.QRect(400, 370, 141, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engWord_4.setFont(font)
        self.VL_engWord_4.setObjectName("VL_engWord_4")
        self.VL_engTransl_4 = QtWidgets.QLabel(self.centralwidget)
        self.VL_engTransl_4.setGeometry(QtCore.QRect(680, 370, 131, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_engTransl_4.setFont(font)
        self.VL_engTransl_4.setAutoFillBackground(False)
        self.VL_engTransl_4.setObjectName("VL_engTransl_4")
        self.VL_rusWord_4 = QtWidgets.QLabel(self.centralwidget)
        self.VL_rusWord_4.setGeometry(QtCore.QRect(550, 370, 141, 41))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VL_rusWord_4.setFont(font)
        self.VL_rusWord_4.setObjectName("VL_rusWord_4")
        self.VocListLabel.hide()
        self.VL_engWord_1.hide()
        self.VL_rusWord_1.hide()
        self.VL_engTransl_1.hide()
        self.VL_engSinonyms_1.hide()
        self.VL_engWord_2.hide()
        self.VL_rusWord_2.hide()
        self.VL_engTransl_2.hide()
        self.VL_engSinonyms_2.hide()
        self.VL_engWord_3.hide()
        self.VL_rusWord_3.hide()
        self.VL_engTransl_3.hide()
        self.VL_engSinonyms_3.hide()
        self.VL_engWord_4.hide()
        self.VL_rusWord_4.hide()
        self.VL_engTransl_4.hide()
        self.VL_engSinonyms_4.hide()

        ### Экран 7 - по кнопке "КАРТОЧКИ"
        self.Palet_2 = QtWidgets.QLabel(self.centralwidget)
        self.Palet_2.setGeometry(QtCore.QRect(385, 90, 301, 321))
        self.Palet_2.setText("")
        self.Palet_2.setObjectName("Palet_2")
        self.Palet_2.setStyleSheet('''
                                                background-color: #e6e6e6;
                                                border-color: #999999;
                                                border-style: outset;
                                                border-width: 2px;
                                                border-radius: 10px;
                ''')

        self.gt_oneWordLabel = QtWidgets.QLabel(self.centralwidget)
        self.gt_oneWordLabel.setGeometry(QtCore.QRect(500, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily(".Tahoma")
        font.setPointSize(18)
        self.gt_oneWordLabel.setFont(font)
        self.gt_oneWordLabel.setObjectName("gt_oneWordLabel")
        self.gt_oneWordLabel.setStyleSheet("background-color: #e6e6e6")

        self.SoundImage = QtWidgets.QLabel(self.centralwidget)
        self.SoundImage.setGeometry(QtCore.QRect(520, 280, 41, 41))
        self.SoundImage.setText("")
        self.SoundImage.setObjectName("SoundImage")
        self.SoundImage.setStyleSheet("background-color: #e6e6e6")

        self.backImage = QtWidgets.QLabel(self.centralwidget)
        self.backImage.setGeometry(QtCore.QRect(410, 350, 41, 41))
        self.backImage.setText("")
        self.backImage.setObjectName("backImage")
        self.backImage.setStyleSheet("background-color: #e6e6e6")

        self.nextImage = QtWidgets.QLabel(self.centralwidget)
        self.nextImage.setGeometry(QtCore.QRect(630, 350, 41, 41))
        self.nextImage.setText("")
        self.nextImage.setObjectName("nextImage")
        self.nextImage.setStyleSheet("background-color: #e6e6e6")

        self.wordImage = QtWidgets.QLabel(self.centralwidget)
        self.wordImage.setGeometry(QtCore.QRect(440, 120, 201, 121))
        self.wordImage.setText("")
        self.wordImage.setObjectName("wordImage")
        self.wordImage.setStyleSheet("background-color: #e6e6e6")

        View_5.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(View_5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 22))
        self.menubar.setObjectName("menubar")
        View_5.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(View_5)
        self.statusbar.setObjectName("statusbar")
        View_5.setStatusBar(self.statusbar)

        self.retranslateUi(View_5)
        QtCore.QMetaObject.connectSlotsByName(View_5)

    def retranslateUi(self, View_5):
        _translate = QtCore.QCoreApplication.translate
        View_5.setWindowTitle(_translate("View_5", "View_5"))
        self.DictLabel.setText(_translate("View_5", "Словарь"))
        self.AddWordButton.setText(_translate("View_5", "Добавить слово"))
        self.MyWordsButton.setText(_translate("View_5", "Мои слова"))
        self.CardsButton.setText(_translate("View_5", "Карточки"))
        pixmap = QPixmap("./img/backNarrow.png")
        self.NackNarrowImage.setPixmap(pixmap)

        ### Экран 5 - по кнопке "ДОБАВИТЬ СЛОВО"
        self.gt_WordLabel.setText(_translate("View_5", "Слово"))
        self.gt_TranslationLabel.setText(_translate("View_5", "Перевод"))

        ### Экран 6 - по кнопке "МОИ СЛОВА"
        self.VocListLabel.setText(_translate("View_5", "Vocabulary List"))
        self.VL_engWord_1.setText(_translate("View_5", "1. sophisticated"))
        self.VL_rusWord_1.setText(_translate("View_5", "утонченный"))
        self.VL_engTransl_1.setText(_translate("View_5", "She has a sophisticated telescope"))
        self.VL_engSinonyms_1.setText(_translate("View_5", "complex, advanced, complicated"))
        self.VL_rusWord_2.setText(_translate("View_5", "утонченный"))
        self.VL_engTransl_2.setText(_translate("View_5", "She has a sophisticated telescope"))
        self.VL_engSinonyms_2.setText(_translate("View_5", "complex, advanced, complicated"))
        self.VL_engWord_2.setText(_translate("View_5", "2. sophisticated"))
        self.VL_rusWord_3.setText(_translate("View_5", "утонченный"))
        self.VL_engTransl_3.setText(_translate("View_5", "She has a sophisticated telescope"))
        self.VL_engSinonyms_3.setText(_translate("View_5", "complex, advanced, complicated"))
        self.VL_engWord_3.setText(_translate("View_5", "3. sophisticated"))
        self.VL_engSinonyms_4.setText(_translate("View_5", "complex, advanced, complicated"))
        self.VL_engWord_4.setText(_translate("View_5", "4. sophisticated"))
        self.VL_engTransl_4.setText(_translate("View_5", "She has a sophisticated telescope"))
        self.VL_rusWord_4.setText(_translate("View_5", "утонченный"))

        ### Экран 7 - по кнопке "КАРТОЧКИ"
        SoundImagepixmap = QPixmap("./img/SoundImage.png")
        self.SoundImage.setPixmap(SoundImagepixmap)
        backImagepixmap = QPixmap("./img/backImage.png")
        self.backImage.setPixmap(backImagepixmap)
        nextImagepixmap = QPixmap("./img/nextImage.png")
        self.nextImage.setPixmap(nextImagepixmap)
        wordImagepixmap = QPixmap("./img/car.png")
        self.wordImage.setPixmap(wordImagepixmap)

        self.gt_oneWordLabel.setText(_translate("View_5", "машина"))

        self.gt_oneWordLabel.hide()
        self.Palet_2.hide()
        self.SoundImage.hide()
        self.backImage.hide()
        self.nextImage.hide()
        self.wordImage.hide()

        def hideAddWord():
            self.gt_WordLabel.hide()
            self.gt_TranslationLabel.hide()
            self.gt_WordtextEdit.hide()
            self.gt_TranslationtextEdit.hide()

        def hideMyWords():
            self.VocListLabel.hide()
            self.VL_engWord_1.hide()
            self.VL_rusWord_1.hide()
            self.VL_engTransl_1.hide()
            self.VL_engSinonyms_1.hide()
            self.VL_engWord_2.hide()
            self.VL_rusWord_2.hide()
            self.VL_engTransl_2.hide()
            self.VL_engSinonyms_2.hide()
            self.VL_engWord_3.hide()
            self.VL_rusWord_3.hide()
            self.VL_engTransl_3.hide()
            self.VL_engSinonyms_3.hide()
            self.VL_engWord_4.hide()
            self.VL_rusWord_4.hide()
            self.VL_engTransl_4.hide()
            self.VL_engSinonyms_4.hide()

        def hideCards():
            self.gt_oneWordLabel.hide()
            self.Palet_2.hide()
            self.SoundImage.hide()
            self.backImage.hide()
            self.nextImage.hide()
            self.wordImage.hide()

        # ПЕРВЫй РАЗДЕЛ
        def clickAddWordButton():
            View_5.resize(715, 570)

            font = QtGui.QFont()
            font.setFamily(".Tahoma")
            font.setPointSize(24)
            font.setWeight(75)
            font.setBold(True)
            self.AddWordButton.setFont(font)

            font = QtGui.QFont()
            font.setFamily(".Tahoma")
            font.setPointSize(24)
            font.setWeight(75)
            font.setBold(False)
            self.MyWordsButton.setFont(font)

            font = QtGui.QFont()
            font.setFamily(".Tahoma")
            font.setPointSize(24)
            font.setWeight(75)
            font.setBold(False)
            self.CardsButton.setFont(font)

            hideMyWords()
            hideCards()

            self.gt_WordLabel.show()
            self.gt_TranslationLabel.show()
            self.gt_WordtextEdit.show()
            self.gt_TranslationtextEdit.show()

        # ВТОРОЙ РАЗДЕЛ
        def clickMyWordsButton():
            View_5.resize(1050, 570)

            font = QtGui.QFont()
            font.setFamily(".Tahoma")
            font.setPointSize(24)
            font.setWeight(75)
            font.setBold(False)
            self.AddWordButton.setFont(font)

            font = QtGui.QFont()
            font.setFamily(".Tahoma")
            font.setPointSize(24)
            font.setWeight(75)
            font.setBold(True)
            self.MyWordsButton.setFont(font)

            font = QtGui.QFont()
            font.setFamily(".Tahoma")
            font.setPointSize(24)
            font.setWeight(75)
            font.setBold(False)
            self.CardsButton.setFont(font)

            hideAddWord()
            hideCards()

            self.VocListLabel.show()
            self.VL_engWord_1.show()
            self.VL_rusWord_1.show()
            self.VL_engTransl_1.show()
            self.VL_engSinonyms_1.show()
            self.VL_engWord_2.show()
            self.VL_rusWord_2.show()
            self.VL_engTransl_2.show()
            self.VL_engSinonyms_2.show()
            self.VL_engWord_3.show()
            self.VL_rusWord_3.show()
            self.VL_engTransl_3.show()
            self.VL_engSinonyms_3.show()
            self.VL_engWord_4.show()
            self.VL_rusWord_4.show()
            self.VL_engTransl_4.show()
            self.VL_engSinonyms_4.show()

        # ТРЕТИЙ РАЗДЕЛ
        def clickCardsButton():
            View_5.resize(715, 570)

            font = QtGui.QFont()
            font.setFamily(".Tahoma")
            font.setPointSize(24)
            font.setWeight(75)
            font.setBold(False)
            self.AddWordButton.setFont(font)

            font = QtGui.QFont()
            font.setFamily(".Tahoma")
            font.setPointSize(24)
            font.setWeight(75)
            font.setBold(False)
            self.MyWordsButton.setFont(font)

            font = QtGui.QFont()
            font.setFamily(".Tahoma")
            font.setPointSize(24)
            font.setWeight(75)
            font.setBold(True)
            self.CardsButton.setFont(font)

            hideAddWord()
            hideMyWords()

            self.gt_oneWordLabel.show()
            self.Palet_2.show()
            self.SoundImage.show()
            self.backImage.show()
            self.nextImage.show()
            self.wordImage.show()


        self.AddWordButton.clicked.connect(clickAddWordButton)
        self.MyWordsButton.clicked.connect(clickMyWordsButton)
        self.CardsButton.clicked.connect(clickCardsButton)